# Generated by Django 5.0.6 on 2024-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='url',
            field=models.CharField(),
        ),
    ]
